/* App state is generated by reducer functions */
/* Books reducer always returns an array of books */
export default function () {
  return [
    { title: 'Picture of Dorian Gray', pages: 264 },
    { title: 'Wuthering Heights', pages: 500 },
    { title: 'Masters of Deception', pages: 85 },
    { title: 'Monstress', pages: 39 }
  ]
}
