/* App state is generated by reducer functions */
/* Books reducer always returns an array of books */
export default function () {
  return [
    { title: 'Picture of Dorian Gray' },
    { title: 'Wuthering Heights' },
    { title: 'Masters of Deception' },
    { title: 'Monstress' }
  ]
}
